vich_uploader:
    db_driver: orm

    mappings:
        avis_image:
            uri_prefix: /uploads/avis
            upload_destination: '%kernel.project_dir%/public/uploads/avis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
